### ISSUE TITLE
A error when running bamboo

### ISSUE THREAD

**Issue by wangduo-ux** [CycloneSEQ-Bioinformatics/Bamboo#16]
hello,
I recently installed and ran the Bamboo for an alignment BAM file (Nanopore) following the author's instructions; however, the following errors occurred. Can you help me address the problem?

2024-11-06 16:31:14 - INFO - Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face (unknown file format; error code 0x2)
2024-11-06 16:31:14 - INFO - generated new fontManager
Traceback (most recent call last):
  File "pandas/__init__.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pandas/_libs/__init__.py", line 13, in <module>
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pandas/_libs/tslibs/__init__.py", line 30, in <module>
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "bamboo/main.py", line 204, in main
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "bamboo/sequence.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "bamboo/plot.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "seaborn/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "seaborn/rcmod.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "seaborn/palettes.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "seaborn/utils.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "pandas/__init__.py", line 33, in <module>
ImportError: C extension: No module named 'pandas._libs.tslibs.base' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --force' to build the C extensions first.
[PYI-2883876:ERROR] Failed to execute script 'main' due to unhandled exception!

**Comment by jzhang-dev** [comment]
Hi, we are currently looking into this issue. Meanwhile, you main try  Bamboo v0.2.1 (https://github.com/CycloneSEQ-Bioinformatics/Bamboo/releases/tag/v0.2.1)  and check whether the issue persists. Thank you.

**Comment by jzhang-dev** [comment]
We have now rebuilt the Bamboo v0.2.2 distribution package and I believe this issue is now fixed. I am closing this issue for now but feel free to reopen it if the problem persists. @wangduo-ux
